### ISSUE TITLE
A parameter property is only allowed in a constructor implementation.

### ISSUE THREAD

**Issue by UltiRequiem** [Exhabition/Tixte-API-Wrapper#1]
The problem is here 👇🏽 

https://github.com/Exhabition/Tixte-API-Wrapper/blob/main/types/index.d.ts#L3

The module should like this 

Reproducible error 👇🏽 

https://github.com/UltiRequiem/sergif/runs/5297985596?check_suite_focus=true

Thanks for the library!

**Comment by Exhabition** [comment]
Sorry for the delay!

I have merged the corresponding PR, thank you for providing one.
Package has been republished

**Comment by UltiRequiem** [comment]
Thanks!
