### ISSUE TITLE
Public && Private

### ISSUE THREAD

**Issue by awgui** [Exhabition/Tixte-API-Wrapper#3]
Can you add options to public or private?

**Comment by Exhabition** [comment]
Of course, I will look at that today, I will also check if any other endpoints need updates :)

**Comment by Exhabition** [comment]
Sorry for the lack of updates on this, I have 2 paid projects that take up most my time, I will add this feature whenever I have free time

**Comment by Exhabition** [comment]
you can now upload files privately by adding `private: true` to the UploadOptions (ca3fee3a6adace4778c8d462d95423ff46e32ac7)

```js
await tixteClient.uploadFile(buffer, domain, { filename, extension, private });
```

I also added the private boolean to UpdateFile, however Tixte doesn't support changing the public/private type after uploading *yet*
